### ISSUE TITLE
plot tab

### ISSUE THREAD

**Issue by bnasr** [bnasr/wiad#28]
error in evaluating the argument 'x' in selecting a method for function 'nrow': object 'data2' not found

**Comment by TTRademacher** [comment]
The problem was that the plots need data (e.g., at least three labels or two growth increments) for detrending. I added a return statement that prevents plotting when there is not enough data and will push the changes later today.

**Comment by dabasler** [comment]
The variable 'data2' is not initialized if is there only one profile.  "Error in nrow: object 'data2' not found"  is thrown when evaluating the following if clause. 
https://github.com/bnasr/wiad/blob/7080fe833aeaa32811d9a06a729dbc739fd0caa6/inst/app/server.R#L1745-L1746
Same issue will arise here https://github.com/bnasr/wiad/blob/7080fe833aeaa32811d9a06a729dbc739fd0caa6/inst/app/server.R#L1759

**Comment by bnasr** [comment]
@dabasler can we close this now?

**Comment by dabasler** [comment]
Yes
