### ISSUE TITLE
Remove useless dependencies

### ISSUE THREAD

**Issue by billy34** [bnasr/wiad#46]
Hello
It seems you are importing `dplyr` just for the pipe (`%>%`) operator. This operator is in the `magrittr` package (`dplyr` just reexport it).
`magrittr` as no real sub dependencies whereas `dplyr` has a lot !
It will vastly reduce the number of packages to install for your users.

**Comment by bnasr** [comment]
Hi @billy34 ,

Thanks for pointing this out. I'll fix and push!

**Comment by TTRademacher** [comment]
I am pretty sure that we are also using a few dplyr specific function, such as join (line 1786 of the server file). I am sure we could replace the few dplyr functions, but just changing the dependencies will probably cause issues.

**Comment by billy34** [comment]
My bad. I overlooked the import of `description` and saw only `namespace`. As you also use `data.table` I assumed your processing was done with it. By the way the joins can be done by `data.table` also :-)
